name: JavaStud CI/CD Pipeline v2.0

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

env:
  JAVA_VERSION: '17'
  MAVEN_VERSION: '3.9.5'

jobs:
  test:
    name:  Testing Suite
    runs-on: ubuntu-latest
    steps:
    - name:  Checkout code
      uses: actions/checkout@v4
    - name:  Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'
    - name:  Setup Maven
      uses: stCarolas/setup-maven@v4
      with:
        maven-version: ${{ env.MAVEN_VERSION }}
    - name:  Run Tests
      run: mvn test
    - name:  Build
      run: mvn clean package

